services:
  app:
    build: .
    container_name: fluently-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=fluently
      - DB_PASSWORD=fluently123
      - DB_NAME=fluently
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules  # nommé ici
    depends_on:
      - postgres
    command: npm run start:dev

  postgres:
    image: postgres:16-alpine
    container_name: fluently-postgres
    restart: always
    environment:
      POSTGRES_DB: fluently
      POSTGRES_USER: fluently
      POSTGRES_PASSWORD: fluently123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: fluently-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fluently.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
  node_modules:   # déclare le volume nommé